version: '3.8'

services:
  ganache-cli:
    container_name: ganache-cli
    image: trufflesuite/ganache-cli:latest
    volumes:
      - ./ganache_data:/ganache_data
    ports:
      - 8545:8545
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --deterministic
      - --db=/ganache_data
      - --mnemonic
      - 'comic control grain goat donate cereal sugar elevator quality limit link soup'
      - --accounts=2

  truffle-dapp:
    container_name: truffle-dapp
    build:
      context: truffle-dapp
    ports:
      - 3000:3000
    tty: true
    command: >
      sh -c "npx truffle compile &&
             npx truffle test &&
             npx truffle migrate &&
             npm run dev"
    volumes:
      - ./truffle-dapp:/app
    depends_on:
      - ganache-cli
